export const DOCS_HOST = "microsoft-4404708b.mintlify.app";
export const DOCS_ORIGIN = `https://${DOCS_HOST}`;

export const JWT_TTL_SECONDS = 10;
export const SESSION_TTL_SECONDS = 60 * 60 * 24 * 14;

/**
 * Replace this value with the PKCS#8 Ed25519 private key generated by the
 * Mintlify JWT settings page. This demo intentionally keeps the key in source
 * to match the requested setup; do not commit or reuse it in production.
 */
export const MINTLIFY_PRIVATE_KEY = `-----BEGIN PRIVATE KEY-----
REPLACE_WITH_MINTLIFY_GENERATED_KEY
-----END PRIVATE KEY-----`;
